language: ruby

rvm:
  - 2.1.1
  - ruby-head
  - jruby-head

notifications:
  email: false

services:
  - elasticsearch

before_install:
  - gem install bundler

before_script:
  - ln -s database.yml.example config/database.yml
  - bundle exec rake secret:replace
  - bundle exec rake db:migrate

script:
  - bundle exec rake test
